apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosuon-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bengo-Hub/mosuon-devops-k8s.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
      include: '*/app.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
